@baseUrl = http://localhost:3000

# RECADOS

### Lista todos os recados
# @name RecadosControllerFindAll
GET {{baseUrl}}/recados/
# ?limit=10
# &offset=10

### Lista apenas um recado
# @name RecadosControllerFindOne
GET {{baseUrl}}/recados/2/

### Cria um recado
# @name RecadosControllerCreate
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "2 NOVO Recado",
  "de": "Maria",
  "para": "Ana"
}

### Atualiza um recado
# @name RecadosControllerUpdate
PATCH  {{baseUrl}}/recados/2/
Content-Type: application/json

{
  "texto": "Recado",
  "lido": true,
} 

### Apaga um recado
# @name RecadosControllerRemove
DELETE   {{baseUrl}}/recados/2/