@baseUrl = http://localhost:3000

# RECADOS

### RecadosControllerFindAll
# @name RecadosControllerFindAll
GET {{baseUrl}}/recados

### RecadosControllerFindOne
# @name RecadosControllerFindOne
GET {{baseUrl}}/recados/:id
