@baseUrl = http://localhost:3000

# RECADOS

### Lista todos os recados
# @name RecadosControllerFindAll
GET {{baseUrl}}/recados/
# ?limit=10
# &offset=10

### Lista apenas um recado
# @name RecadosControllerFindOne
GET {{baseUrl}}/recados/1/

### Cria um recado
# @name RecadosControllerCreate
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "recado": "Este é o recado que estou enviando.",
  "nova chace": "outro valor"
}

### Atualiza um recado
# @name RecadosControllerUpdate
PATCH  {{baseUrl}}/recados/1/
Content-Type: application/json

{
  "recado": "Este é o recado que estou enviando.",
  "atualizar": true
}

### Apaga um recado
# @name RecadosControllerRemove
DELETE   {{baseUrl}}/recados/1/